codecov:
  notify:              # [advanced] usage only
    after_n_builds: 3  # how many build to wait for before submitting notifications


coverage:
  status:
    project:                   # measuring the overall project coverage
      default:                 # context, you can create multiple ones with custom titles
        target: auto              # specify the target coverage for each commit status
        threshold: 10%            # allowed to drop X% and still result in a "success" commit status

    patch:
      default:
        target: auto                 # specify the target "X%" coverage to hit
        threshold: 20%              # allowed to drop X% and still result in a "success" commit status


comment: false  # to disable comments
