OSU::AccessPolicy.register(User, UserAccessPolicy)
OSU::AccessPolicy.register(ContactInfo, ContactInfoAccessPolicy)
OSU::AccessPolicy.register(EmailAddress, ContactInfoAccessPolicy)
OSU::AccessPolicy.register(ApplicationUser, ApplicationUserAccessPolicy)
OSU::AccessPolicy.register(Message, MessageAccessPolicy)
OSU::AccessPolicy.register(Group, GroupAccessPolicy)
OSU::AccessPolicy.register(GroupMember, GroupMemberAccessPolicy)
OSU::AccessPolicy.register(GroupOwner, GroupOwnerAccessPolicy)
