# config/app.yml for rails-settings-cached

defaults: &defaults
  push_salesforce_lead_enabled: false
  user_info_error_emails_enabled: false
  send_google_analytics: false
  google_analytics_code: UA-73668038-2
  google_tag_manager_code: GTM-W6N7PB
  sheer_id_base_url: https://offers.sheerid.com/openstax/staging/teacher/?env=dev
  number_of_days_contacts_modified: 7

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
