# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause this
# file to always be loaded, without a need to explicitly require it in any files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, make a
# separate helper file that requires this one and then use it only in the specs
# that actually need it.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # These two settings work together to allow you to limit a spec run
  # to individual examples or groups you care about by tagging them with
  # `:focus` metadata. When nothing is tagged with `:focus`, all examples
  # get run.
  #config.filter_run :focus
  config.run_all_when_everything_filtered = true

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = 'doc'
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  #config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  #config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed

  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # Enable only the newer, non-monkey-patching expect syntax.
    # For more details, see:
    #   - http://myronmars.to/n/dev-blog/2012/06/rspecs-new-expectation-syntax
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
    expectations.syntax = :expect
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Enable only the newer, non-monkey-patching expect syntax.
    # For more details, see:
    #   - http://teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/
    mocks.syntax = :expect

    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended.
    mocks.verify_partial_doubles = false
  end

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = '.rspec_last_failures'
end

"" "
  Rspec matcher definitions
" ""
RSpec::Matchers.define_negated_matcher :not_change, :change

RSpec::Matchers.define :have_routine_error do |error_code|
  include RSpec::Matchers::Composable

  match do |actual|
    actual.errors.any? { |error| error.code == error_code }
  end

  failure_message do |actual|
    "expected that #{actual} would have error :#{error_code.to_s}"
  end
end

RSpec::Matchers.define :have_api_error_code do |error_code|
  include RSpec::Matchers::Composable

  match do |actual|
    actual.body_as_hash[:errors].any? { |error| error[:code] == error_code }
  end

  failure_message do |actual|
    "expected that response would have error '#{error_code.to_s}' but had #{actual.body_as_hash[:errors].pluck(:code)}"
  end
end

RSpec::Matchers.define :have_api_error_status do |error_status|
  include RSpec::Matchers::Composable

  match do |actual|
    actual.body_as_hash[:status] == error_status.to_i
  end

  failure_message do |actual|
    "expected that response would have status '#{
      error_status}' but had #{actual.body_as_hash[:status]}"
  end
end

RSpec::Matchers.define :have_error do |field, message|
  include RSpec::Matchers::Composable

  match do |actual|
    actual.errors.types.include? field and actual.errors.types[field].include? message
  end

  failure_message do |actual|
    if actual.errors[field].empty?
      "expected #{actual.model_name} to have errors on #{field}, but it had none"
    else
      msg = error_msg actual.class, field, message
      "expected #{actual.errors[field]} to include #{msg.inspect}"
    end
  end

  failure_message_when_negated do |actual|
    msg = error_msg actual.class, field, message
    "expected #{actual.errors[field]} not to include #{msg.inspect}"
  end
end


"" "
  Custom helper methods
" ""
# Utility for getting error messages for models. It's intended as a replacement
# for have_error matcher to be used when there is no model instance. For example
#
#   visit '/redefine/model/instance'
#   expect(page).to have_content(error_msg Model, :id, :taken)
#
# There two alternative signatures
#
# error_msg model, field, error, options = {}
# error_msg model, group, field, error, options = {}
#
# First form expects model to be an ActiveRecord model, a Lev handler with
# a single paramify block, or a symbol naming one.
#
# Second form expects a Lev handler with a paramify block named group, or
# a symbol naming one.
def error_msg(model, *args)
  model_or_name = model
  if model.is_a? Symbol
    model = Object.const_get model.to_s.camelize
  end
  if model.include? Lev::Handler
    if args[-1].is_a? Hash
      options = args.pop
    else
      options = {}
    end
    if args.length == 3
      group, field, error = args
    elsif args.length == 2 and model.paramify_classes.keys.length == 1
      field, error = args
      group = model.paramify_classes.keys[0]
    end
    model = model.paramify_classes[group]
    if model.nil?
      raise "#{model_or_name} is a Lev handler but is not paramified"
    end
  else
    field, error, options = args
  end
  options ||= {}
  instance = model.new
  if options.has_key? :value
    instance[field] = options[:value]
  end
  options[:message] = error
  Lev::BetterActiveModelErrors.generate_message instance, field, :invalid, options
end

# From: https://github.com/rspec/rspec-rails/issues/925#issuecomment-164094792
# See also: https://github.com/codeforamerica/ohana-api/blob/master/spec/api/cors_spec.rb
#
# Add support for testing `options` requests in RSpec.
# See: https://github.com/rspec/rspec-rails/issues/925
def options(*args)
  reset! unless integration_session
  integration_session.__send__(:process, :options, *args).tap do
    copy_session_variables!
  end
end

def in_docker?
  ENV.fetch('HUB_URL', false)
end
