class UpgradeDoorkeeper < ActiveRecord::Migration
  def up
    # This migration is the result of comparing
    # db/migrate/20130717010545_create_doorkeeper_tables.rb
    # and the new migration generated by doorkeeper 1.4.2
    change_column :oauth_applications, :redirect_uri, :text
    change_column :oauth_access_grants, :redirect_uri, :text, null: false, limit: nil
    change_column :oauth_access_tokens, :application_id, :integer, null: true
  end

  def down
    change_column :oauth_applications, :redirect_uri, :string
    change_column :oauth_access_grants, :redirect_uri, :string
    change_column :oauth_access_tokens, :application_id, :integer, null: false
  end
end
