---
resources:
  - name: accounts-deployment-git
    type: git
    source:
      uri: git@github.com:/openstax/devops
      branch: tutor-deployment-update
      private_key: ((github-private-key))

  - name: accounts-git
    type: git
    source:
      uri: git@github.com:openstax/accounts.git
      private_key: ((github-private-key))
      branch: new-deployment

  - name: accounts-deployment-docker-image
    type: docker-image
    source:
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: openstaxdevops/accounts-deployment

jobs:
  - name: publish-deployment-image
    plan:
      - get: accounts-deployment-git
        trigger: true
      - put: accounts-deployment-docker-image
        params:
          build: accounts-deployment-git/new_deployments/apps/accounts

  - name: sandbox-build-create-test-delete
    plan:
      - get: accounts-deployment-docker-image
        passed: [publish-deployment-image]
      - get: accounts-git
        trigger: true

      - task: build-ami
        image: accounts-deployment-docker-image
        file: accounts-git/concourse/build-ami/task.yml

      - task: create-release-candidate-environment
        image: accounts-deployment-docker-image
        file: accounts-git/concourse/create-release-candidate-environment/task.yml

      - task: delete-release-candidate-environment
        image: accounts-deployment-docker-image
        file: accounts-git/concourse/delete-release-candidate-environment/task.yml
