class NewflowUi.EducatorComplete

  constructor: ->
    _.bindAll(@, 'onRoleChange', 'onHowUsingChange', 'onHowChosenChange')
    @form = $('.signup-page.completed-step')
    @completed_role = @form.find('.completed-role')
    @completed_role.change(@onRoleChange)
    @please_select_role = @form.find('.role.newflow-mustdo-alert')
    @please_select_using = @form.find('.using.newflow-mustdo-alert')
    @please_select_chosen = @form.find('.chosen.newflow-mustdo-alert')
    @continue = @form.find('#signup_form_submit_button')
    @how_chosen = @form.find('.how-chosen')
    @how_using = @form.find('.how-using')
    @how_using.change(@onHowUsingChange)
    @how_chosen = @form.find('.how-chosen')
    @how_chosen.change(@onHowChosenChange)
    @other_specify = @form.find('.other-specify')
    @how_chosen = @form.find('.how-chosen')
    @subjects_interest = @form.find('.subjects-of-interest')
    @total_num_students = @form.find('.total-num-students')
    @books_used = @form.find('.books-used')
    this.onRoleChange()
    this.onHowUsingChange()
    this.initMultiSelect()
    @continue.attr('disabled', 'disabled')
    @please_select_role.show()
    @please_select_using.show()

  initMultiSelect: ->
    subjects_interest = document.getElementById('signup_subjects_of_interest')
    osMultiSelect(subjects_interest)
    books_used = document.getElementById('signup_books_used')
    osMultiSelect(books_used)

  onRoleChange: ->
    @please_select_role.hide()
    @continue.removeAttr('disabled')
    if ( $('#signup_completed_role_educator').is(':checked') )
      @other_specify.hide()
      @books_used.hide()
      @how_using.show()
      @how_chosen.show()
      @total_num_students.show()
    else if ( $('#signup_completed_role_admin').is(':checked') )
      @other_specify.hide()
      @books_used.hide()
      @total_num_students.hide()
      @how_chosen.show()
      @how_using.show()
    else if ( $('#signup_completed_role_other').is(':checked') )
      @books_used.hide()
      @how_chosen.hide()
      @subjects_interest.hide()
      @total_num_students.hide()
      @how_using.hide()
      @other_specify.show()
    else
      @books_used.hide()
      @how_chosen.hide()
      @subjects_interest.hide()
      @total_num_students.hide()
      @how_using.hide()
      @other_specify.hide()

  onHowUsingChange: ->
    @please_select_using.hide()
    if ( $('#signup_using_as_primary').is(':checked') )
      @books_used.show()
      @how_chosen.show()
      @subjects_interest.hide()
    else if ( $('#signup_using_as_recommending').is(':checked') )
      @books_used.show()
      @how_chosen.show()
      @subjects_interest.hide()
    else if ( $('#signup_using_as_future').is(':checked') )
      @books_used.hide()
      @how_chosen.show()
      @subjects_interest.show()
    else
      @books_used.hide()
      @how_chosen.hide()
      @subjects_interest.hide()

  onHowChosenChange: ->
    @please_select_chosen.hide()
