class NewflowUi.EducatorComplete

  constructor: ->
    _.bindAll(@, 'onRoleChange', 'onHowUsingChange')
    @form = $('.signup-page.completed-step')
    @completed_role = @form.find('.completed-role')
    @completed_role.change(@onRoleChange)
    @how_using = @form.find('.how-using')
    @how_using.change(@onHowUsingChange)
    @other_specify = @form.find('.other-specify')
    @how_chosen = @form.find('.how-chosen')
    @subjects_interest = @form.find('.subjects-of-interest')
    @total_num_students = @form.find('.total-num-students')
    @books_used = @form.find('.books-used')
    this.onRoleChange()
    this.onHowUsingChange()
    this.initMultiSelect()

  initMultiSelect: ->
    subjects_interest = document.getElementById('signup_subjects_of_interest')
    osMultiSelect(subjects_interest)
    books_used = document.getElementById('signup_books_used')
    osMultiSelect(books_used)

  onRoleChange: ->
    if ( $('#signup_completed_role_educator').is(':checked') )
      @other_specify.hide()
      @books_used.hide()
      @how_using.hide()
      @how_chosen.show()
      @total_num_students.show()
      @subjects_interest.show()
    else if ( $('#signup_completed_role_admin').is(':checked') )
      @other_specify.hide()
      @books_used.hide()
      @how_chosen.hide()
      @total_num_students.hide()
      @how_using.show()
      @subjects_interest.show()
    else if ( $('#signup_completed_role_other').is(':checked') )
      @books_used.hide()
      @how_chosen.hide()
      @subjects_interest.hide()
      @total_num_students.hide()
      @how_using.hide()
      @other_specify.show()

  onHowUsingChange: ->
    if ( $('#signup_using_as_primary').is(':checked') )
      @books_used.show()
    else if ( $('#signup_using_as_recommended').is(':checked') )
      @books_used.hide()
    else if ( $('#signup_using_as_future').is(':checked') )
      @books_used.hide()
      @how_chosen.show()
      @subjects_interest.show()
