---
http_interactions:
- request:
    method: post
    uri: "<salesforce_instance_url_lower>/services/data/v37.0/sobjects/Lead"
    body:
      encoding: UTF-8
      string: '{"FirstName":"Essie","LastName":"Swift","Company":"unknown to Accounts","Email":"f@f.com","LeadSource":"OSC
        Faculty","Newsletter__c":false,"Newsletter_Opt_In__c":false,"OS_Accounts_ID__c":4,"accounts_uuid_c__c":"947713b1-ee76-4d3d-b375-9a37a42149a0","Application_Source__c":"Tutor
        Signup","Role__c":"instructor","FV_Status__c":"pending_faculty","FV_Final__c":true,"Needs_CS_Review__c":false}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Authorization:
      - OAuth <salesforce_access_token>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Wed, 19 Aug 2020 22:57:42 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://a.forcesslreports.com/hpkp-report/00DR0000001zq0Zm";
      Expect-Ct:
      - max-age=86400, report-uri="https://a.forcesslreports.com/Expect-CT-report/00DR0000001zq0Zm"
      X-Robots-Tag:
      - none
      X-B3-Traceid:
      - 450dff463bd584a8
      X-B3-Spanid:
      - 450dff463bd584a8
      X-B3-Sampled:
      - '0'
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=Y17dVOJvEeqbf6mTy029xQ; domain=.salesforce.com; path=/; expires=Thu,
        19-Aug-2021 22:57:42 GMT; Max-Age=31536000
      Sforce-Limit-Info:
      - api-usage=6317/51000
      Location:
      - "/services/data/v37.0/sobjects/Lead/00QR000000KBmCFMA1"
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"id":"00QR000000KBmCFMA1","success":true,"errors":[]}'
    http_version:
  recorded_at: Wed, 19 Aug 2020 22:57:44 GMT
- request:
    method: get
    uri: "<salesforce_instance_url_lower>/services/data/v37.0/query?q=SELECT%20Id,%20Name,%20FirstName,%20LastName,%20Salutation,%20Subject__c,%20Company,%20Phone,%20Website,%20Status,%20Email,%20LeadSource,%20Newsletter__c,%20Newsletter_Opt_In__c,%20Adoption_Status__c,%20Number_of_Students__c,%20OS_Accounts_ID__c,%20accounts_uuid_c__c,%20Application_Source__c,%20Role__c,%20who_chooses_books__c,%20FV_Status__c,%20FV_Final__c,%20Needs_CS_Review__c%20FROM%20Lead%20WHERE%20(Id%20=%20%2700QR000000KBmCFMA1%27)%20LIMIT%201"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.17.3
      Authorization:
      - OAuth <salesforce_access_token>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 19 Aug 2020 22:57:44 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://a.forcesslreports.com/hpkp-report/00DR0000001zq0Zm";
      Expect-Ct:
      - max-age=86400, report-uri="https://a.forcesslreports.com/Expect-CT-report/00DR0000001zq0Zm"
      X-Robots-Tag:
      - none
      X-B3-Traceid:
      - a2ccb298eb9ccd3d
      X-B3-Spanid:
      - a2ccb298eb9ccd3d
      X-B3-Sampled:
      - '0'
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=ZLSCjOJvEeqmmnVkoS5CRA; domain=.salesforce.com; path=/; expires=Thu,
        19-Aug-2021 22:57:44 GMT; Max-Age=31536000
      Sforce-Limit-Info:
      - api-usage=6318/51000
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"totalSize":1,"done":true,"records":[{"attributes":{"type":"Lead","url":"/services/data/v37.0/sobjects/Lead/00QR000000KBmCFMA1"},"Id":"00QR000000KBmCFMA1","Name":"Essie
        Swift","FirstName":"Essie","LastName":"Swift","Salutation":null,"Subject__c":null,"Company":"unknown
        to Accounts","Phone":null,"Website":null,"Status":"Converted","Email":"f@f.com","LeadSource":"OSC
        Faculty","Newsletter__c":false,"Newsletter_Opt_In__c":false,"Adoption_Status__c":"High
        Interest in Adopting","Number_of_Students__c":30.0,"OS_Accounts_ID__c":"4","accounts_uuid_c__c":"947713b1-ee76-4d3d-b375-9a37a42149a0","Application_Source__c":"Tutor
        Signup","Role__c":"Faculty","who_chooses_books__c":null,"FV_Status__c":"pending_faculty","FV_Final__c":true,"Needs_CS_Review__c":false}]}'
    http_version:
  recorded_at: Wed, 19 Aug 2020 22:57:44 GMT
recorded_with: VCR 3.0.3
