name: Linting
on:
  pull_request:
  push:
    branches: main
jobs:
  linting:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: lint
      BUNDLE_WITHOUT: development:test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rubocop --format progress
