---
http_interactions:
- request:
    method: get
    uri: "<salesforce_instance_url>/services/data/v51.0/query?q=SELECT%20Id,%20Email,%20Email_alt__c,%20FV_Status__c,%20School_Type__c,%20Adoption_Status__c,%20Grant_Tutor_Access__c,%20Accounts_UUID__c,%20Account.Id,%20Account.Name,%20Account.BillingCity,%20Account.BillingState,%20Account.BillingCountry,%20Account.Type,%20Account.School_Location__c,%20Account.SheerID_School_Name__c,%20Account.K_I_P__c,%20Account.child_of_kip__c%20FROM%20Contact%20WHERE%20(Accounts_UUID__c%20!=%20null)%20AND%20(LastModifiedDate%20%3E=%202022-01-14T00:00:00Z)"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v1.0.1
      Authorization:
      - OAuth <salesforce_access_token>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 21 Jan 2022 21:47:50 GMT
      Set-Cookie:
      - BrowserId=x-vLvXsDEeyf_lspu3mJhw; domain=.salesforce.com; path=/; expires=Sat,
        21-Jan-2023 21:47:51 GMT; Max-Age=31536000
      - CookieConsentPolicy=0:1; path=/; expires=Sat, 21-Jan-2023 21:47:51 GMT; Max-Age=31536000
      - LSKey-c$CookieConsentPolicy=0:1; path=/; expires=Sat, 21-Jan-2023 21:47:51
        GMT; Max-Age=31536000
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Sforce-Limit-Info:
      - api-usage=8047/5000000
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"totalSize":2,"done":true,"records":[{"attributes":{"type":"Contact","url":"/services/data/v51.0/sobjects/Contact/0034C00000XQDaCQAX"},"Id":"0034C00000XQDaCQAX","Email":"ecw1+cs@rice.edu","Email_alt__c":null,"FV_Status__c":"pending_faculty","School_Type__c":"College/University
        (4)","Adoption_Status__c":"Not Adopter","Grant_Tutor_Access__c":false,"Accounts_UUID__c":"1a48905c-b67a-440a-9b3a-60368c3a4bf7","Account":{"attributes":{"type":"Account","url":"/services/data/v51.0/sobjects/Account/0014C00000dkLkoQAE"},"Id":"0014C00000dkLkoQAE","Name":"Rice
        University","BillingCity":"Houston","BillingState":"Texas","BillingCountry":"United
        States","Type":"College/University (4)","School_Location__c":"Domestic","SheerID_School_Name__c":"Rice
        University (Houston, TX)","K_I_P__c":false,"child_of_kip__c":false}},{"attributes":{"type":"Contact","url":"/services/data/v51.0/sobjects/Contact/0034C00000X5gJRQAZ"},"Id":"0034C00000X5gJRQAZ","Email":"be12+409@rice.edu","Email_alt__c":null,"FV_Status__c":"confirmed_faculty","School_Type__c":"College/University
        (4)","Adoption_Status__c":"Not Adopter","Grant_Tutor_Access__c":false,"Accounts_UUID__c":"a336f40a-de7d-4a84-8d6b-c2c3ea2f7a7e","Account":{"attributes":{"type":"Account","url":"/services/data/v51.0/sobjects/Account/0014C00000dkKQAQA2"},"Id":"0014C00000dkKQAQA2","Name":"Test
        University","BillingCity":null,"BillingState":null,"BillingCountry":"United
        States","Type":"College/University (4)","School_Location__c":"Domestic","SheerID_School_Name__c":"Test
        University","K_I_P__c":false,"child_of_kip__c":false}}]}'
    http_version: 
  recorded_at: Fri, 21 Jan 2022 21:47:51 GMT
recorded_with: VCR 3.0.3
